#!/bin/sh
conf=/tmp/etc/smb.conf
usbpath=$1
disk="$(echo $usbpath | sed -n 's/.*\///p')"
sed '/\['"$disk"'\]/,/write list/d' $conf > $conf.tmp
for pid in `ps -w | grep smbd | grep -v grep | awk '{print $1}'`
do
	kill $pid
done
for pid in `ps -w | grep nmbd | grep -v grep | awk '{print $1}'`
do
	kill $pid
done
cp $conf.tmp $conf
smbd -D $conf
nmbd -D $conf